[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
name = "chakra"
version = "0.1.0"

[dependencies]
error-chain = "0.5.0"
libc = "0.2.17"

[dependencies.chakra-sys]
path = "chakra-sys"
